version: '3.8'

services:
    user:
        build:
            context: ./userService
        image: microservice/user
        restart: "no"
        environment:
            - DB_URI=mongodb://mongo:27017/
            - DB_NAME=team-workspace
        ports:
            - 8001:50051
        depends_on:
            - mongo

    project:
        build:
            context: ./projectService
        image: microservice/project
        restart: "no"
        environment:
            - DB_URI=mongodb://mongo:27017/
            - DB_NAME=team-workspace
        ports:
            - 8002:50052
        depends_on:
            - mongo

    entity:
        build:
            context: ./entityService
        image: microservice/entity
        restart: "no"
        environment:
            - DB_URI=mongodb://mongo:27017/
            - DB_NAME=team-workspace
        ports:
            - 8003:50053
        depends_on:
            - mongo

    api:
        build:
            context: ./apiService
        image: microservice/api
        restart: "no"
        environment:
            - DB_URI=mongodb://mongo:27017/
            - DB_NAME=team-workspace
        ports:
            - 8010:8000
        depends_on:
            - mongo

    mongo:
        image: mongo
        restart: "no"
        environment:
            MONGO_INITDB_DATABASE: team-workspace
        ports:
            - 27017:27017
